### ISSUE TITLE
Create GSOC proposal

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#106]
via INCF we'll try to get a google summer of code intern. General idea is to make a two-option proposal with Brent on using LLMs for 

1. first-pass data annotation
2. natural language graph searches

Proposal should go here: https://docs.google.com/document/d/1q5PMMW5_hFUaVgbTncOKfAPOLzzsDLPzFRpS5NHq1Zs/edit?usp=sharing

Due date is February 6th

**Comment by alyssadai** [comment]
Closing as we have submitted our proposal, h/t @rmanaem 🎉
