### ISSUE TITLE
Reprocess all Neurobagel-hosted datasets

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#107]
For alignment with:
- https://github.com/neurobagel/bagel-cli/pull/234
- https://github.com/neurobagel/bagel-cli/pull/250
- https://github.com/neurobagel/bagel-cli/pull/260
- https://github.com/neurobagel/bagel-cli/pull/264

### Steps before implementing
- [x] ~Confirm we have not missed session ID columns existing in OpenNeuro participants.tsvs~
  - longitudinal phenotypic data is not BIDS-compliant
- [x] Chat with Nipoppy team about PD multi-session data

### Steps to implement
Use bagelcli v0.2.1

- Update:
  - [x] INDI 
    - [x] re-run CLI
      - need to update CLI version in local copy of script
    - [x] update data repo
      -  See https://github.com/neurobagel/indi-annotations/pull/3
  - [x] QPN
    - [x] update data dictionary
    - [x] re-run CLI
  - [x] PPMI
    - [x] update data dictionary
    - [x] re-run CLI
  - [x] OpenNeuro
    - [x] Do not bother w/ updating forks for now, just rerun CLI on current data we have
      - need to update CLI version in local copy of script
      - See details on new failures here https://hackmd.io/@neurobagel/B1lbGZLTT#2024-04-02-JSONLD-update
    - [x] update data repo
      - See https://github.com/neurobagel/openneuro-annotations/pull/8

This will have to happen before we can deploy our newly released APIs because data model has changed

**Comment by surchs** [comment]
@alyssadai I crossed out the session ID check for ON datasets. If that existed it would not be valid BIDS. If it does exist we definitely didn't get it. But I don't think we should go back / add those. That'll have to wait for a BIDS compliant solution because ON requires BIDS

**Comment by surchs** [comment]
Blocked by query tool -> API redeployment

We should talk about the order we want to do this in

**Comment by rmanaem** [comment]
Unblocked and can be done in parallel with the redeployment of query tool and f-API.

**Comment by alyssadai** [comment]
Notes from PD data dictionary updating:
- "REM sleep behavior disorder" (used in QPN) is not a diagnosis term option in the annotation tool but is available in SNOMED: https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=415238003
  - Maybe related to the level of depth it's at relative to the disease terms we took?

**Comment by alyssadai** [comment]
For reviewer:

Can check an example JSONLD file in (can look for the new `nb:ImagingSession` and `nb:PhenotypicSession` instances)
- INDI: https://github.com/neurobagel/indi-annotations/tree/main/data
- OpenNeuro: https://github.com/neurobagel/openneuro-annotations
- QPN: see `/data/pd/qpn/tabular/neurobagel`
- PPMI: see `/data/pd/ppmi-new/tabular/neurobagel`

**Comment by surchs** [comment]
Thank you very much @alyssadai for taking this on and documenting it. Reviewed and found to be good 🎉 

🧑‍🍳
