### ISSUE TITLE
Set up neurobagel email accounts

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#115]
We need a non-person email for the BIC, and we'll need these for other reasons soon as well.

To start us of, we should have:

- info@neurobagel.org
- admin@neurobagel.org

Tasks
- [x] research and propose an easy solution for how we can get an email address with our own domain (neurobagel.org)
  - [x] without hosting our own mailserver
  - [x] with a high chance of making it through spam filters
  - [ ] ideally for low to no cost
  - [ ] with IMAP enabled
- [x] set up the email account
- [x] store the passwords in the Bitwarden vault

**Comment by alyssadai** [comment]
another option: team@neurobagel.org :)

**Comment by alyssadai** [comment]
https://www.namecheap.com/hosting/email/

**Comment by surchs** [comment]
As far as I can tell, the only free option would be

- https://developers.cloudflare.com/email-routing/

This just forwards email to our personal / work emails. So we can receive but not send.

Other options:
- https://www.namecheap.com/hosting/email/
- https://www.zoho.com/mail/zohomail-pricing.html
- https://proton.me/mail/pricing (only one user)

Also this person made a massive spreadsheet with comparisons: https://docs.google.com/spreadsheets/d/1Gu8FFyNY1Y9X69kHmJvkI0fLv8GaK-5B6HnQZZzo1Nw/edit?usp=sharing

**Comment by surchs** [comment]
My view is: let's start with the Cloudflare email solution. Reasons:

- free (we'd have to discuss if it's worth to pay money for custom email)
- we already each have emails - so receiving them in the regular mailbox is pretty easy
- the downside of having to respond from a personal email address to an email for neurobagel is OK (to me)

I'll make a follow-on issue to actually implement this if we all agree.

**Comment by surchs** [comment]
we might also be able to combine this / use instead: https://documentation.mailgun.com/docs/mailgun/user-manual/get-started/

**Comment by surchs** [comment]
I'm going to close this. Our setup is now:

- Cloudflare for receiving email
- Own email / McGill email for responding
- google-groups: https://groups.google.com/g/neurobagel for disseminating newsletter-like info (tbd)
