### ISSUE TITLE
Update the copyright of all licenses

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#116]
Split off from https://github.com/neurobagel/project/issues/171, we want to directly update the copyright on our licenses to include:

- McGill
- the Origami Lab
- Neurobagel developers (already there for most / all)

on all repos. We don't want to change the type of the license in this issue, that's going to be discussed in https://github.com/neurobagel/project/issues/171

For Review
- [ ] https://github.com/neurobagel/api/pull/279
- [ ] https://github.com/neurobagel/bagel-cli/pull/276
- [ ] https://github.com/neurobagel/query-tool/pull/374
- [ ] https://github.com/neurobagel/react-query-tool/pull/30
- [ ] https://github.com/neurobagel/documentation/pull/167
- [ ] https://github.com/neurobagel/federation-api/pull/71
- [ ] https://github.com/neurobagel/annotation_tool/pull/693
- [ ] https://github.com/neurobagel/recipes/pull/20
- [ ] https://github.com/neurobagel/digest/pull/139
- [ ] https://github.com/neurobagel/bagelschema/pull/7
- [ ] https://github.com/neurobagel/neurobagel_examples/pull/27
- [ ] https://github.com/neurobagel/menu/pull/8

**Comment by rmanaem** [comment]
Feel free to close once all PRs go in.
