### ISSUE TITLE
Deploy INDI cloud instance with graph+API+query tool

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#119]
- [x] Deploy another stack on fairmount
- [x] add a new subdomain, e.g. indi.neurobagel.org with the registrar
- [x] handle the new route on NGINX
- [x] add data to the INDI node
- [x] confirm that it is reachable directly
- [x] confirm the node is reachable via federation

**Comment by surchs** [comment]
To deploy, I ran `docker run --rm -d --name=api-indi -p 8001:8000 --env-file=.env --network bagelapi_default neurobagel/api:stable` locally

**Comment by alyssadai** [comment]
Thanks @surchs. I've added the `indi` database to our internal table of nodes [here](https://github.com/neurobagel/documentation/wiki/API#neurobagel-hosted-apis), and can confirm that queries show INDI datasets. 🎉

I've also tried using `dataget` to download the data for one ABIDE dataset locally, which seems to work as expected.

Once the comments in https://github.com/neurobagel/planning/issues/117 are addressed, I think we can close this 👍

**Comment by surchs** [comment]
Closing as #117 is completed.
