### ISSUE TITLE
create federated INDI node

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#13]
we have an OpenNeuro endpoint (https://github.com/neurobagel/project/issues/104) that is publicly visible. These data are great for showing the technical feasibility of neurobagel, but most datasets lack phenotypic depth, i.e. they don't have much information beyond age and sex. FCP/INDI is a collection of curated datasets with rich(er) phentoypic information that have been used many times. These data are also 

- open access
- in BIDS
- in datalad

so they are a natural extension for neuroabgel. Although FCP/INDI is not technically a data publishing platform (like OpenNeuro), they are for our purposes the "owners" of these data. So we will ingest these data into a second endpoint with the goal of having the endpoint be taken over eventually by INDI itself.

An important parallel objective required by the second endpoint is to develop query federation. We want to be able to scale the neurobagel ecosystem to many future endpoints - for now limited to fully open data that do not require authentication.

Architecture discussion: https://miro.com/app/board/uXjVMmLP5VI=/?share_link_id=37602049569

# Why
- part of #11 
- follows #17 
- follows #35
- to grow the findable data in neurobagel with interesting metadata / that people will use for actual research
- to understand and solve the technical challenges with query federation across neuroabgel endpoints
- so that we are ready to scale the neurobagel ecosystem to more endpoints in the future
- so we can go to the INDI folks and ask them to take this endpoint over / work with us to add retrospective and prospective non-fully-open datasets
- to go and have a more concrete startingpoint to talk with COINSTAC about having their own neurobagel endpoint

# Outcomes
- [x] we're running a second, public neurobagel endpoint for [FCP/INDI](http://fcon_1000.projects.nitrc.org/) (eventually we want to hand this over to the actual data owners)
- [x] the following open INDI datasets are annotated and findable in the endpoint
  - [x] ABIDE 1: http://fcon_1000.projects.nitrc.org/indi/abide/abide_I.html
  - [x] ABIDE 2: http://fcon_1000.projects.nitrc.org/indi/abide/abide_II.html
  - [x] ADHD200: http://fcon_1000.projects.nitrc.org/indi/adhd200/index.html
  - [x] CORR: http://fcon_1000.projects.nitrc.org/indi/CoRR/html/index.html
- [x] the datasets are `dataget`-able: https://datasets.datalad.org/
- [x] there is a web query interface that allows me to search over the INDI endpoint AND the OpenNeuro endpoint at the same time (federation)

# What
- [x] Determine licensing / DUA for phenotypic INDI data
- [x] #117
- [x] #118
- [x] #119

**Comment by Remi-Gau** [comment]
## Some facts
- ABIDE 1 and 2, CORR, ADHD200 are getable from datalad superdataset
- all split by one dataset per site
- some do not have participants.tsv
- none has a participants.json

## Questions:

### Generating / storing annotated data dictionaries

- generate with annotation tool or the way we did it for openneuro?
- can we assume all site specific datasets can share a common annotated data dictionary?
- create a sibling of each site specific dataset and dump the annotated data dictionary in it? or just a simple repo that hosts only the annotated data dictionaries?
- should we start simple (only age and sex) and them to the graph and then add more columns?

**Comment by surchs** [comment]
Closing as completed. INDI node is running, see #117 for details about the process
