### ISSUE TITLE
Reupload data to our public and local graphs

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#139]
- Make copy of JSONLDs on appropriate servers

### Public
- [x] INDI
  - [x] JSONLDs in GitHub repo
  - [x] vocab
  - note: can use `gh` CLI (run `gh auth login` first, and use browser option to authenticate) to 'login' to acct so you can clone private repo w/o have an ssh key in cloud server
- [x] QPN
  - [x] JSONLDs on BIC
  - [x] vocab
- [x] PPMI
  - [x] JSONLDs on BIC
  - [x] vocab
- [x] OpenNeuro
  - [x] JSONLDs in GitHub repo
  - [x] vocab

See also https://hackmd.io/@neurobagel/SkgLzb86a#Neurobagel-hosted-APIs

### Local
- [x] BIC internal node (database called `bic_pd`)
  - [x] QPN
  - [x] PPMI
  - [x] vocab

REDEPLOY SERVICES (with new versions) ON:
- [x] st-viateur
- [x] fairmount
- [x] homemade

**Comment by alyssadai** [comment]
Blocked until n-API / f-API / query tool (?) are re-released

**Comment by alyssadai** [comment]
Blocked by some API and query tool performance fixes.

**Comment by alyssadai** [comment]
- For reviewer: see new public nodes now tracked in our status page via neurobagel/upptime#5
- `homemade` services can be checked when connected to McGill network:
  - https://api-bic.neurobagel.org
  - https://query-bic.neurobagel.org
  - https://federate-bic.neurobagel.org

**Comment by surchs** [comment]
🎉 🧑‍🍳 🥳
