### ISSUE TITLE
Addressing VM issues

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#154]
Notes documenting the sequence of actions/events: https://hackmd.io/@neurobagel/BknZ2z1UR

**Comment by surchs** [comment]
@rmanaem what's the state of things with the VM and vGPUs? Could you link your notes on this?

**Comment by rmanaem** [comment]
> what's the state of things with the VM and vGPUs? Could you link your notes on this?

Unfortunately, it's still unclear what led to the drivers stop working as expected. After the last crash, I rebuilt the machine and installed the latest CUDA toolkit following Michael's (CC support) instructions.
I also added the link to hackmd containing my notes to the issue description.

**Comment by surchs** [comment]
Thanks for the detailed notes! So for now it's running?

Let's see what happens next, and in a week or so we should let support know either way

**Comment by rmanaem** [comment]
This issue is blocked as we wait for the DRC tech support to get back to us on the remaining issue: making a snapshot of Fabrique instance.
