### ISSUE TITLE
Complete workflow for uploading a user-submitted OpenNeuro annotation

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#166]
### Why

- Part of goal: 
- Currently only Neurobagel members can change JSON files in OpenNeuroDatasets-JSONLD

### Outcomes

- [ ] Any user should be able to submit and annotation and have a PR opened

### What

- [x] https://github.com/neurobagel/ui/issues/91
- [x] https://github.com/neurobagel/tools/issues/24
- [x] https://github.com/neurobagel/workflows/issues/106

**Comment by surchs** [comment]
@alyssadai we can close this Milestone, right? I think all of this is done
