### ISSUE TITLE
Neurobagel can search IDPs

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#167]
# Context
Rolling out nipoppy to collaborators

# Why
- So we can find IDPs

# Outcomes
- [x] The Neurobagel data model understands IDPs
- [x] A user who has used Nipoppy to generate IDPs can tell Neurobagel about them with no additional manual tasks (other than running tools)
- [x] A user can search for subjects processed with a given pipeline and version
- [x] There exists a list (vocabulary) of standardized pipeline names that nipoppy knows about (each with their known version names)

# What
Nipoppy:
- [x] Create or get examples of the nipoppy imaging bagel format for testing
- [ ] Get a copy of the imaging bagel validation schema from Nipoppy
- [x] Create vocabulary repo with one file per pipeline

Neurobagel:
- [x] https://github.com/neurobagel/neurobagel_examples/issues/33
- [x] https://github.com/neurobagel/bagel-cli/issues/342
- [x] https://github.com/neurobagel/bagel-cli/issues/262
- [x] https://github.com/neurobagel/api/issues/341
- [x] neurobagel/recipes#88
- [x] neurobagel/api#344
- [x] https://github.com/neurobagel/federation-api/issues/113
- [x] https://github.com/neurobagel/federation-api/issues/117
- [x] https://github.com/neurobagel/query-tool/issues/282
- [x] neurobagel/documentation#230
- [x] Re-release:
  - [x] f-API
  - [x] n-API
  - [x] query tool
  - [x] CLI
- [ ]  https://github.com/neurobagel/bagel-cli/issues/352

**Comment by alyssadai** [comment]
Closing as all key issues have been addressed; we will address https://github.com/neurobagel/bagel-cli/issues/352 separately as it is currently blocked by https://github.com/neurobagel/bagel-cli/issues/180.
