### ISSUE TITLE
technical demonstration of query federation

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#17]
We've shown that neuroabgel can run with one instance. To grow, we need to be able to federate across several instances. 
Because direct access to the SPARQL endpoint / graph is impossible by design,  we likely cannot rely on SPARQLs builtin federation ability and will have to federate at the API level.
We need a first prototype for this, so that we can discuss and improve from there.
Thus: "practical >> perfect" for this one

## Why
- part of #11 
- design and prototype federation
- demonstrate capability to federate
- set the conditions for neurobagel to grow quickly by adding endpoints

## Outcome
- there are two neurobagel endpoints I can reach from the public internet (data don't matter, but more than 2)
- we have a first draft of a federated API architecture that supports search
- I can write one query, that results in responses from both endpoints (new and existing OpenNeuro public)

## How

**prep**:

- [x] #18
- [x] #19
  - is there something ready-to-go we can use?
- [x] #20
- [x] #21
  - what services
  - who talks to whom?
  - who collects / assembles results

**implement**:
- [x] create federation endpoint that I can send a query to
- [x] successfully run a federated query with results

**cleanup**:
- [x] https://github.com/neurobagel/planning/issues/31

**Comment by alyssadai** [comment]
I think this issue can be closed when https://github.com/neurobagel/planning/issues/31 is closed.
