### ISSUE TITLE
Take down the old website

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#178]
https://neurobagel.github.io/ is still reachable, although we have archived https://github.com/neurobagel/neurobagel.github.io earlier this year. The issue is that the domain is pretty memorable, and also the root-domain of our current development docs: https://neurobagel.github.io/dev-docs/ - so easy to get to.

Probably some folks also land on the old website via google 🤷 

So my point is that we should:

-  [x] make sure make sure https://neurobagel.github.io/ either reroutes to our official docs or 
- [ ] replace the contents of https://neurobagel.github.io/ with something else that also has a clear and visible link to the official website.

**Comment by rmanaem** [comment]
For reviewer: visit the old website at https://neurobagel.github.io/. It should redirect to our neurobagel.org

**Comment by surchs** [comment]
Nice, confirm that this is addressed!
