### ISSUE TITLE
create a second public neurobagel endpoint (API + Graph) and fill it with some data

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/planning#18]
Steps that need to happen here:

Remote setup
- [x] neurobagel/planning#24
- [x] #26

Local setup

- [x] neurobagel/api#187 (not planned for now)

**Comment by surchs** [comment]
@neurobagel/dev 

- make cloud machine B reachable and run its own API + graph
  - figure out if we need NGINX for https
  - if no https, make sure both endpoints can handle http
- cloud machine A (with OpenNeuro currently): make a second API + Graph deployment
  - figure out how we can reach that new API from outside (e.g NGINX updates?, domains?)

@surchs 

- see if there is an easy way to deploy two endpoints on the same local computer, using basic makefile

**Comment by alyssadai** [comment]
@surchs, is this good to close?

**Comment by alyssadai** [comment]
Closing as all subtasks are completed
