### ISSUE TITLE
Migrate the CLI to pydantic v2

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#180]
### Context

Pydantic v2 has been out for quite a bit. The CLI (and the nodes) are still on v1. That is starting to cause some limitations, e.g. we cannot easily reuse nipoppy schema in our tools because nipoppy is on v2 (with breaking changes).

### Why

- keep code maintainable
- compatibility with nipoppy (and other projects)

### Outcomes

- [x] CLI uses pydantic v2
- [x] all tests are still green
- [ ] nothing else has changed

### What

- [x] https://github.com/neurobagel/bagel-cli/issues/180

**Comment by alyssadai** [comment]
Yes - closing!
