### ISSUE TITLE
Deploy the MNI node with authentication enabled

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#181]
Context

- will do it on FAIRMOUNT
- full-stack deployment with a dockerized query tool (with AUTH enabled)
- we will (re-)use the NGINX setup to get a custom domain
- should be aggregated (for now)

Steps

- [x] Get a custom domain for the query tool and the f-API (but not the n-API)
- [x] Do the actual deployment (from current recipes)
- [x]  Go to the google console and update our OIDC app
- [x] confirm our users are whitelisted on Google who can authenticate

URLs for the services will be:
- https://api-bic.neurobagel.org
- https://federate-bic.neurobagel.org
- https://query-bic.neurobagel.org

**Comment by surchs** [comment]
@alyssadai looks like these are all addressed, very cool! Can we close the issue?

**Comment by alyssadai** [comment]
Yes, I think so!
