### ISSUE TITLE
Give auth-access to the PIs for the MNI-PD node

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#182]
- [x] collect the email addresses of users we want to give access to the node (privately, not in the issue!)
- [x] add these emails to the Auth app
- [x] Test that the whitelist works by
  - [x] check I can login with email from whitelist
  - [x] check I can not login with other email

**Comment by alyssadai** [comment]
Blocked by lack of whitelist capabilities by Google right now, switching to different OIDC provider

**Comment by alyssadai** [comment]
Notes:

We cannot send email invitations to users (https://auth0.com/docs/customize/email/send-email-invitations-for-application-signup) without configuring a custom email provider. However, we _can_ create password reset links for specific users (https://auth0.com/docs/api/management/v2/tickets/post-password-change), or trigger a password reset request email to be sent to specific users (https://auth0.com/docs/api/authentication#change-password), using the Auth0 API. (Note: For at least the former, I needed to enable (?) the Auth0 Management API to get a token for the API explorer.)

To make it easier for whitelisted users to reset their password after we first create their user accounts, we will send password reset emails to users via curl requests.

**Comment by alyssadai** [comment]
Blocked until we get the go-ahead from JB to send emails to PIs.
