### ISSUE TITLE
Annotate and extract metadata for the Calgary dataset

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#183]
- [x] Annotate
- [x] Extract (only phenotypic + bids data for now)
- [x] Load into the Node in aggregated mode

Data location: `~/dataplace/data/bic_internal/closed`
Recipe location: `~/dataplace/projects/bic_internal_nodes/closed`

**Comment by surchs** [comment]
For now the Calgary dataset will only be discoverable 

- to selected, logged in MNI users
- in aggregated mode

**Comment by alyssadai** [comment]
All tasks are complete (thanks @michellewang for your help!) - I've updated the iss description with the data and recipe locations.
