### ISSUE TITLE
Regenerate and upload MNI PD JSONLD files

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#184]
Once 
- https://github.com/nipoppy/nipoppy/pull/354 is merged, 

we need to regenerate derivative files for:
- [x] QPN - non-agg
- [x] PPMI - agg
- [x] Calgary - agg (and on CC)

steps:
- [x] pull the latest (`latest`) version of the CLI with `docker pull neurobagel/bagel-cli:latest` / `singularity pull bagel.sif docker://neurobagel/bagelcli`
- [x] regenerate the processing status files with nipoppy
- [x] rerun the CLI (all 3 steps: `pheno`, `bids`, `derivatives`)

and collect feedback (if any) from the nipoppy folks

Next,
- Upload the new .jsonld files into graph databases:
  - [x] PPMI
  - [x] QPN
  - [x] Calgary

**Outcomes:**
- Two new nodes on BIC:
  - `McConnell Brain Imaging Centre - Aggregated` (containing PPMI, Calgary)
    - recipe location: `~/dataplace/projects/bic_internal_nodes/closed`
    - data location: `~/dataplace/data/bic_internal/closed`
  - `McConnell Brain Imaging Centre - Open` (containing QPN)
    - recipe location: `~/dataplace/projects/bic_internal_nodes/open`
    - data location: `~/dataplace/data/bic_internal/open`

**Comment by surchs** [comment]
@michellewang and @mathdugre, these are the steps we need for our PD node

**Comment by surchs** [comment]
The latest bagelcli is `neurobagel/bagelcli:v0.3.0`: https://hub.docker.com/repository/docker/neurobagel/bagelcli/tags

**Comment by alyssadai** [comment]
Currently blocked by neurobagel/bagel-cli#369

**Comment by alyssadai** [comment]
Hey @nikhil153, would you have capacity to regenerate the Neurobagel JSONLD file for the QPN following this issue?

**Comment by alyssadai** [comment]
Tasks are now complete - I updated the iss description with the final node names and locations on `fairmount`.
