### ISSUE TITLE
Collect API query federation frameworks for inspiration

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/planning#19]
List of resources for us to split up and read about:

- http://docs.genomebeacons.org/other-implementations/#progenetix-api
  - https://b2ri-documentation.readthedocs.io/en/latest/endpoints/individuals.html#tag/GET-Endpoints/operation/getOneIndividualBiosamples similar to our new vocabulary-list endpoints
  - e.g. also: http://progenetix.org/beacon/filtering_terms/?filters=PMID
  - adopting a generic specification that can be implemented by endpoints: http://docs.genomebeacons.org/framework/
  - https://github.com/ga4gh-discovery/data-connect
- https://the-guild.dev/graphql/mesh
- https://hasura.io/products/federation
  - https://hasura.io/docs/latest/data-federation/hasura-graphql-federation-architectures/
- https://www.w3.org/TR/sparql11-federated-query/

**Comment by surchs** [comment]
we discussed this yesterday: https://miro.com/app/board/uXjVMhZMs9c=/?share_link_id=808931575999 and although all these frameworks have a lot of overlap with what we're doing, we need to get a better sense of what we're looking for. So for our first simple prototype, we'll go with a very basic approach that we setup ourselves. Then we'll come back to review these frameworks. I'll close this issue
