### ISSUE TITLE
Update our OBI.json to .tsv script so it also reads the sample.json files (where the assessments / instruments are)

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#193]

**Comment by alyssadai** [comment]
For reviewer:

Process for defining assessment columns from `*_samples.json` when generating the TSV:
- If sample has modality `clinical`, grab the `instrument` name. Then, find the matching subject (`participant_id`) for the sample in the existing TSV (created just from the `*_participants.json`) and add a new column for the instrument with a value of `"completed"` for that subject

**Comment by surchs** [comment]
Thanks! Where did you put the script you used to convert from OBI .json to .tsv?

With that, I think we can close 🧑‍🍳

**Comment by alyssadai** [comment]
@surchs, here's a private repo containing the conversion script and different versions of the data we've generated so far (just for tracking purposes):
https://github.com/neurobagel/project-obi
