### ISSUE TITLE
Re-generate the .tsv files for the OBI synthetic data to include assessments / instruments and re-annotate them, and re-generate .jsonld files

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#196]
- [x] share the .jsonld files with the OBI and make sure that they can load and then find these datasets

**Comment by alyssadai** [comment]
Some notes on the process:
- Needing to re-annotate the entire dataset from scratch was a bit annoying
- Some aspects of the assessment tool annotation are still a little non-user-friendly, particularly:
  - User first identifies all columns in their TSV about any assessment, and then matches them to specific assessments from CogAtlas. However, if assessments are not found in CogAtlas, user has to go back up to the initial column categorization and remember & de-select all of the ones that they couldn't annotate
  - Not being able to search by instrument abbreviations
  - The UI for the assessment-to-column matching is a little "bulky", in that when verifying columns for each assessment, I have to scroll through the entire list including the ones I have annotated as being about other assessments
    - Some initial ideas: maybe we could use a two-column layout for the column names, such that the ones annotated with the currently selected assessment are all grouped together? or otherwise visually group them somehow

**Comment by surchs** [comment]
Thanks @alyssadai, these are all very good points about the annotation tool. I think it'd make sense to discuss them even before the bigger changes we have planned and see what could be quickly addressed.
