### ISSUE TITLE
Create data dictionary for first Douglas dataset

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#2]
As part of https://github.com/neurobagel/project/issues/105#top we want to create a valid data dictionary for the first Douglas dataset with Matt.

Based on Matt's manually created draft data dictionary (using the annotation tool as a guide) on the CIC, we will:
- [x] manually update the .json to be compliant with our schema (https://neurobagel.org/dictionaries/)
- [x] run a prelim check that the first step of the CLI does not complain about the data dictionary/TSV format
- [x] send .json back to Matt for verification

**Comment by surchs** [comment]
@alyssadai anything I should look at for review here? Or did you just mean to close it?

**Comment by alyssadai** [comment]
Think we can close this issue as complete.
