### ISSUE TITLE
Design simple first federation architecture

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/planning#21]
We want to have something very simple for now that let's a user 

- take a single action to trigger a query process
- that results in responses from two separate neurobagel APIs
- and returns the results in a way that lends itself to combination for the users consumption (e.g. via GUI)

First rough sketch is:

![Image](https://github.com/neurobagel/planning/assets/1302022/bc7ce8d9-18ce-491f-ba68-dc11060fe865)

i.e. we're probably going to have a new, central service that does the federation for us. Other ideas were discussed here: https://miro.com/app/board/uXjVMhZMs9c=/?share_link_id=159730087206

The idea would be to spell the above sketch out in enough detail that we can start building the entire thing.

Some constraints:

- Ability to query multiple graphs behind APIs shouldn't be blocked if a central federation engine goes down
- Should be able to accommodate different API architectures
- 90% won't want to talk to db's directly ?

Open questions (add as needed)

- what if two endpoints have the same data
- what if one endpoint returns aggregate data and the other returns everything?
- do we return full results on the first query, or just names and sample size

**Comment by surchs** [comment]
Closing as we implemented this as a first prototype
