### ISSUE TITLE
Add second API + graph deployment to cloud server with OpenNeuro currently

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#26]
On `graph-db-tester`:

- [X] Create new directory `~/projects_test` containing some OpenNeuro data and a copy of the API repo
- [X] Create second Stardog root containing license: `~/stardog_root_test`
- [X] Create new DB: `test_data`, uses default admin credentials
- [x] Database should hold first 10 datasets from https://github.com/neurobagel/openneuro-annotations:
  ```
  ds000001.jsonld
  ds000002.jsonld
  ds000003.jsonld
  ds000005.jsonld
  ds000006.jsonld
  ds000007.jsonld
  ds000008.jsonld
  ds000009.jsonld
  ds000011.jsonld
  ds000017.jsonld
  ```
- [ ] ~Check if NGINX needs to be updated~
  - [x] No, we can just add a new OpenStack security group rule (`graph_db_tester federation rules`) for the instance that allows traffic to the port we're exposing the API on
- [x] Check if API can be accessed using IP + port: http://206.12.99.17:8888/

**Comment by rmanaem** [comment]
For reviewer: You can send a request to the IP address of the machine or check the stack running on the machine.

**Comment by surchs** [comment]
I have reviewed the new API and have confirmed that it is running beautifully 🎉 👍 🧑‍🍳
