### ISSUE TITLE
Set up HTTPS support for federation API subdomain

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#29]
- [x] Ensure the machine listens only on port 80 and/or 443
- [x] Request an SSL certificate (via CertBot)
- [x] Update query tool repository variable `API_QUERY_URL` to point to `https://federate.neurobagel.org`

**Comment by alyssadai** [comment]
For reviewer: you can test this out by navigating to `https://federate.neurobagel.org/`

(note that like `api.neurobagel.org`, the NGINX config has been set up so that navigating to the root will redirect you automatically to `/docs` for an easier user experience)

**Comment by surchs** [comment]
All looks great! Good to close 🧑‍🍳
