### ISSUE TITLE
Prepare federation API to query OpenNeuro graph and a new INDI graph DB

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#30]
- [x] #33
- [x] #31
- [x] On second machine, add new db to the graph server which will eventually house INDI data. For now, just add our synthetic BIDS dataset
  - [x] #32

**Comment by surchs** [comment]
@rmanaem

**Comment by rmanaem** [comment]
@surchs I don't think this the "point public query tool to `open_neuro` issue. Could you confirm?

**Comment by alyssadai** [comment]
I think it is @rmanaem. I believe we still want the query tool to point to the federation API so we can demonstrate federation over 2 nodes, but we want to have one of the federation "nodes" be the `open_neuro` API. The second checkbox is probably most relevant here. The third is to try and ensure we don't have duplicates between the two nodes (I don't know how the query tool will handle that right now), but could be split off into a separate issue.

**Comment by rmanaem** [comment]
> The second checkbox is probably most relevant here

I see. Yea I was referring to the issue as a whole. I was wondering how to address it since we don't have FCP/INDI yet. However, as you suggested it's better to address the checkboxes (2nd in this case) separately.

**Comment by rmanaem** [comment]
So right now the node api and the federation api on the first machine (please remind me of the name) have been updated and running the latest docker images.
Aside from renaming the database that hosts the synthetic data to `INDI` on the 2nd machine is there anything else to be done to complete this issue?

**Comment by alyssadai** [comment]
@rmanaem thank you!!

> Aside from renaming the database that hosts the synthetic data to INDI on the st_viateur is there anything else to be done to complete this issue?

>

**Comment by alyssadai** [comment]
@rmanaem thank you!!

> Aside from renaming the database that hosts the synthetic data to INDI on the st_viateur is there anything else to be done to complete this issue?

I think this is up to you - it doesn't take long to create a new database so if you would prefer to keep things separate, I think we could address https://github.com/neurobagel/planning/issues/32 separately and remove it from the issue tasks. 🤷

**Comment by rmanaem** [comment]
I think it's better to rename the current database to `indi` instead of creating a new one. And when the `indi` data is available simply update the database.

**Comment by rmanaem** [comment]
Once #32 is closed we can close this.
