### ISSUE TITLE
Federation API should point to the URL for the node API currently pointing to the `open_neuro` database (https://api.neurobagel.org/)

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/planning#31]
- [x] Update the `NEUROBAGEL_NODES` in federation_api clone on the server to include the api pointing to `open_neuro` graph
- [x] Build the image
- [x] Stop the current container and run a new container based on the newly created image

**Comment by rmanaem** [comment]
For reviewer: Please check the federation_api clone on the server or run an empty query on the [public query tool](https://query.neurobagel.org/) you should be able to see 10 duplicate datasets.

**Comment by surchs** [comment]
Looks good @rmanaem. I think we have fixed the duplicates since you wrote this, correct? Right now I see 353 datasets with an empty query - and that's good. We can close this issue
