### ISSUE TITLE
Annotation tool: feature complete

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#35]
### Context

The annotation tool has been sitting at "almost ready" for a long while, and we'd like it to join the rest of the party of "look, it works". Here we're focusing purely on the technical aspect of having the required functionality. But there are other aspects such as ease of use and guidance that we will address soon after. 

See for more context: https://docs.google.com/document/d/1jzAWI6dzBCYVPsdczt3U49flOuWRPSOdDQmU9dBRelM/edit?usp=sharing

### Why

- Part of neurobagel/planning#11 
- To enable new node-sites to annotate data on their own
- To make sure users have a good experience for the entire workflow, and they tend to start with annotations
- So that we can use our own tools to add data to nodes we're currently maintaining
- To deliver on our commitments to our friends and collaborators who want to reuse this tool

### Outcomes

- [x] Tool creates a valid bagel.json, i.e.: I can give the file to the CLI and it'll be happy with it
- [x] I can classify "healthy control" as part of the diagnosis annotation workflow
- [x] The discrete value mapping dropdowns give me all valid options to choose from (e.g. diagnosis -> SNOMED-CT)
- [x] I can annotate assessment tools

### What

- [x] https://github.com/neurobagel/annotation_tool/issues/585
- [x] https://github.com/neurobagel/annotation_tool/issues/477
- [x] https://github.com/neurobagel/annotation_tool/issues/285
- [x] https://github.com/neurobagel/annotation_tool/issues/597
- [x] neurobagel/annotation_tool#589
  - [x] https://github.com/neurobagel/annotation_tool/issues/238
  - [x] https://github.com/neurobagel/annotation_tool/issues/591
- [x] https://github.com/neurobagel/annotation_tool/issues/553
- [x] ~~Ensure there's no `MissingValues` key for a column when it has no missing values~~
  - e.g. `"MissingValues": []` --> this should not happen ?
  - CLI doesn't mind empty missingValues
- [x] https://github.com/neurobagel/planning/issues/52

**Comment by surchs** [comment]
@alyssadai / @rmanaem, can you take a look to
- see if we're missing any implementation things ("What")
- if there are existing issues that cover the non-issueified steps
- have any other notes

**Comment by alyssadai** [comment]
Added a couple related issues under `What`. This list otherwise looks good to me!

**Comment by rmanaem** [comment]
@alyssadai When you get a chance could you see if CLI is happy with the output of the annotation tool with the new changes?
We can then check the last item on the outcomes `Tool creates a valid bagel.json, i.e.: I can give the file to the CLI and it'll be happy with it` and close this.
