### ISSUE TITLE
MNI PD data part of public federation

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#36]
### Context

We have PD data in nipoppy and neurobagel but have taken down the search interface / demo for them in favour of the public OpenNeuro query endpoint. The PD data are cool, and our users want to search them. We should find ways to make the PD data queryable in a way that respects their specific characteristics. 

It is important to clearly communicate and show that we are providing a cross-dataset view at the participant level, and not recreate the work of a local database.

### Why

- Part of goal: neurobagel/planning#11
- So MNI users (and possibly others) can query cohorts across more than one PD dataset
- To enhance the quality and amount of findable data
- To understand the data governance constraints of non-public data in a semi-public search context (e.g. aggregate only, yes/no only, full results ...)
- To communicate to MNI users what it is that neurobagel does, how it is different from a database, and why it is useful to them

### Outcomes

- [x] We know what the external constraints are for making PD data publicly queryable
- [ ] If possible, there is now a web interface I can go to search cohorts across QPN and PPMI
- [ ] ~~If possible, I can get phenotypic information of my cohort if I have the necessary permissions (e.g. encryption)~~
- [x] I can find out the sample size across QPN and PPMI that fit specific cohort criteria

### What

- [x] Clarify what constraints exist to make local PD data queryable with a public endpoint (yes/no result, aggregate, full, ...) -> JB
- [x] neurobagel/planning#39
- [x] neurobagel/planning#44
- [x] Understand if node constraints are interoperable with the rest of the neurobagel network, and connect the PD nodes if possible
- [ ] ~provide a query interface that can be constrained to only the PD data API endpoints~
- [x] https://github.com/neurobagel/query-tool/issues/262
- [x] Make a list of API results returned in aggregate mode so that we can individually OK them
- [x] neurobagel/api#208
- [x] neurobagel/api#210

**Comment by alyssadai** [comment]
@surchs, the only subtask left is:

> provide a query interface that can be constrained to only the PD data API endpoints

Currently, there is no query tool running that federates over only the PPMI and QPN, but our public federation API is pointing to OpenNeuro as well as the two PD databases. Do we still want to have the former?

Otherwise, I think this milestone is complete.
