### ISSUE TITLE
Add link to Neurobagel documentation in all repo READMEs

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#41]
These repos need to get a link to our general docs, ideally to a tool specific position:

- [x] https://github.com/neurobagel/annotation_tool
- [x] https://github.com/neurobagel/query-tool
- [x] https://github.com/neurobagel/api
- [x] https://github.com/neurobagel/bagel-cli
- [x] https://github.com/neurobagel/federation-api
- [x] https://github.com/neurobagel/proc_dash

**Comment by surchs** [comment]
For reviewer: please review one of the PRs in these repos. I'll close when they are all merged

**Comment by surchs** [comment]
All PRs are merged.
