### ISSUE TITLE
Create separate nodes for the PPMI and QPN

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#44]
Ideally, these datasets would live on two different different databases (with different APIs) in the same graph server.

In order to allow two different APIs to talk to the same graph container, we may need to create a new docker-compose.yml or otherwise connect one of the API container to an existing docker network (see https://docs.docker.com/engine/reference/commandline/network_connect/).

### Steps to implement
- [x] Launch GraphDB container on `st-viateur` and add two new PD databases (`mni_ppmi` and `mni_qpn`)
- [ ] Launch `api_qpn` along with graph stack in ~non-aggregated~ aggregate mode
- [x] Launch `api_ppmi` in aggregate mode
- [x] Add `api_ppmi` to `api_qpn` Docker network (arbitrary) and ~rename network~
  - [x] verify via interactive docs that `api_ppmi` can reach a db in the graph container
- [x] **for easier relaunching, create a custom docker-compose.yml for the PD databases**
  - under `~/projects/pd_compose`
  - values for non-API variables hardcoded in the yml
- [x] Ensure both are accessible without vpn
  - [x] Update security rules for `st-viateur` to allow ingress on each new API's port

**Comment by alyssadai** [comment]
For reviewer, see on `st-viateur`:
- database-specific .env files and docker-compose.yml at `~/projects/pd_compose`
- contents of docker network `pd_compose_default` (default name based on compose config location) using:
  `docker network inspect pd_compose_default`
- newly created PD GraphDB databases, with `curl -u "admin:<PASSWORD>" http://localhost:7200/repositories`

**Comment by surchs** [comment]
Thanks @alyssadai! All config files look great, excellent choice of credentials. However I am getting error 403 from the QPN API:

```
{"detail":": Forbidden (HTTP status 403)\n"}
```

I'm assuming that's not what we want?

**Comment by alyssadai** [comment]
Thanks for catching that @surchs.

I've re-granted RW permissions to both the `mni_qpn` and `mni_ppmi` databases for the database user I set up. If you try to access the QPN API again it should now work.

I've also opened an issue to document the (problem of) non-additive permissions here https://github.com/neurobagel/documentation/issues/116.

**Comment by alyssadai** [comment]
Hey @surchs, following recent discussions about the privacy of QPN I've updated the API config for the `mni_qpn` database to run in aggregate mode as well.

Let me know if this issue looks good to close now 🙂

**Comment by surchs** [comment]
@alyssadai I checked the requests and it now works for me with no auth error! Thanks a lot. I think we can close
