### ISSUE TITLE
Filter SNOMED-CT terms to children of "disorders of central nervous system"

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#52]
**context**:
https://github.com/neurobagel/annotation_tool/issues/591 shows how to get the terms from SNOMED-CT via OHDSI/Athena.

This results in a download with the following .csv files (that are in fact .tsv):

- CONCEPT.csv - the actual terms (and quite a bit of meta-concepts?). We are interested in the ones that are of `domain_id` "Condition" and also `standard_concept` = "S"
- CONCEPT_RELATIONSHIP.csv - a table of (I think) relationships between concepts. What we are probably interested in are the relationships of type `relationship_id` = "Is a" - as this indicates subclass relationship
- CONCEPT_ANCESTOR.csv - not quite clear, but this could be a table that contains all children of all terms up to a certain degree of separation. Might be worth looking into. A quick ctrl-f for `376106` finds a couple of hits, so maybe that's all we need for now?
- a bunch of other stuff that I haven't figured out yet.

The parent concept we're looking for is "disorder of the central nervous system": https://athena.ohdsi.org/search-terms/terms/376106. So we probably want to get everything that has a "Is a" relationship where "disorder of the central nervous system" is the subject, and then so on. 

There are probably many good ways of modeling these. This does look like a nice graph-problem, so representing the relationship table as a graph with either networkx https://networkx.org/documentation/stable/tutorial.html or even https://rdflib.readthedocs.io/en/stable/ might be helpful - but whatever it takes.

outcomes:
- [x] a piece of code that goes from the downloaded .csv files to a .json file of the desired form
- [x] a .json file that contains only concepts that are
  - child concepts of "disorder of the central nervous system" / 376106
  - child concepts of "mental disorder" / 432586
  - are of type `domain_id` "Condition"
  - are of `standard_concept` "S"
- [x] with their preferred label (human readable label)
- [ ] make sure that all the current diagnosis terms in the `open_neuro` graph are in the end result

**Comment by surchs** [comment]
@neurobagel/dev take a look and see if we're missing any info. Whoever takes this on either has to make an account with OHDSI/Athena to get the SNOMED vocab or I will have to share my copy

**Comment by alyssadai** [comment]
Athena concept ID is not the same as the term ID used by bioportal (technically "notation"). Equivalence is bioportal ID = Athena concept code.

E.g.:
http://purl.bioontology.org/ontology/SNOMEDCT/35919005
35919005 = bioportal ID = SCTID = Athena concept code

**Comment by rmanaem** [comment]
Here is the code to do most of what this issue describes:

```Python3
import pandas as pd
from rdflib import Graph, RDFS

# Load the CONCEPT_RELATIONSHIP.csv and filter for parent-child relationship ("Is a")
df = pd.read_csv("./CONCEPT_RELATIONSHIP.csv", sep='\t', usecols=['concept_id_1', 'concept_id_2', 'relationship_id'])
df = df[df['relationship_id'] == "Is a"]

# Save the parent-child relationships as triples to an rdflib Graph object to query over
graph = Graph()

for index, row in df.iterrows():
    concept_id_1 = row['concept_id_1']
    concept_id_2 = row['concept_id_2']
    graph.add((Literal(concept_id_1), RDFS.subClassOf, Literal(concept_id_2)))

# Save the graph into a .ttl file to run queries faster and easier
graph.serialize(format="turtle", destination="graph.ttl")

# Load the graph using the .ttl file
graph = Graph()
graph.parse("./graph.ttl")

query = """
SELECT ?child
WHERE {
   {?child rdfs:subClassOf* 432586}
   UNION
   {?child rdfs:subClassOf* 376106}
  
}
"""

# Run the query and grab the (Athena) concept_id for each term
query_results = graph.query(query)
diagnosis_concept_ids = [int(res[0]) for res in query_results]

# Load the CONCEPT.csv to map the (Athena) concept_id to concept_code (bioportal concept_id)
df1 = pd.read_csv("CONCEPT.csv", sep="\t")
diagnosis_term_ids = df1[df1['concept_id'].isin(diagnosis_concept_ids) & (df1["domain_id"] == "Condition") & (df1["standard_concept"] == "S")]["concept_code"].to_list()

# Compare the terms to the terms in the open_neuro graph
import csv

open_neuro_diagnosis_term_ids = []

with open("test_query_sparql_results.csv", "r") as file:
    csv_reader = csv.reader(file)

    for row in csv_reader:
        if len(row[0]) < 20:
            continue
        open_neuro_diagnosis_term_ids.append(int(row[0][46:]))


for diag in open_neuro_diagnosis_term_ids:
    if diag not in diagnosis_term_ids:
        print(diag)

# Structure the dataframe for json output
diagnosis_terms_df = df1[df1['concept_code'].isin(diagnosis_term_ids)][['concept_code', 'concept_name']]
diagnosis_terms_df = diagnosis_terms_df.rename(columns={'concept_code': 'identifier', 'concept_name': 'label'})
diagnosis_terms_df = diagnosis_terms_df.reset_index(drop=True)
diagnosis_terms_df['identifier'] = 'snomed:' + diagnosis_terms_df['identifier'].astype(str)

# Save to json file
diagnosis_terms_df.to_json("./diagnosisTerms.json", orient="records")
```

**Comment by rmanaem** [comment]
> make sure that all the current diagnosis terms in the open_neuro graph are in the end result

As discussed we are currently missing 6 terms that are present in the `open_neuro` but not in this newly curated list:

| BioPortal id   |      Label   |
|----------|:-------------:|
| 432119003 | Aneurysm |
| 87486003 | Aphasia |
| 59770006 |    Dyslexia |
| 203082005 |  Fibromyalgia |
| 238131007 | Overweight |
| 397540003 | Visual impairment |

**Comment by surchs** [comment]
@rmanaem, I think this looks good as a future reference. I added two comments in the code for things I think I might forget. With that, we can

- [ ] open a PR to merge the JSON you created here into the annotation tool repo
- [ ] close this issue
