### ISSUE TITLE
Not all datasets in graph are returned for empty query

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#54]
Currently, there are 340 datasets and 20656 subjects in the `open_neuro` graph, but only 333 datasets, 16201 subjects are returned when running an empty query using the query tool (so 7 datasets are missing)

We've encountered this a few times, and one hypothesis is that the current query sent by the API assumes there's at least one session per subject in each dataset, but subjects with only phenotypic data currently don't have sessions due to our data model. As a result, it’s possible that datasets with subjects who have imaging data that can’t be modelled somehow just never match any API query to the graph (?).

In other words, this is likely a problem with the complex query template in the API. We should investigate using Stardog Studio whether we can modify the template to get equal numbers of datasets/subjects as when we query for each number individually.

_Originally posted by @alyssadai in https://github.com/neurobagel/planning/issues/50#issuecomment-1789808127_

Tasks
- [x] collect all dataset IDs (ds0012345...) or unique IDs (ephemeral graph IDs) from inside the open_neuro graph
- [x] do the same, but via query against the API or the query tool (e.g. download .tsv)
- [x] make a diff of the two lists
- [x] list the difference here, making sure to cover both directions, e.g.
  - missing: dataset is in the graph but not in the query result
  - phantom: dataset is not in the graph but in the query result 🤷 
- [x] find out what is special about the diff-datasets and post it here

**Comment by alyssadai** [comment]
For reviewer:

The list of missing datasets (in `open_neuro` graph but not in query tool result) are:
```
ds002912
ds002939
ds002982
ds003967
ds003082
ds003754
ds002718
```

### What's the problem?
Based on inspecting these datasets in https://github.com/OpenNeuroDatasets, it does appear the problem is as initially suspected, which is that the imaging data available in these datasets cannot be modeled by the CLI and thus the subjects have no (imaging) session info in the resulting JSONLD. Since the query template used in the API assumes that all subjects have at least one session (see https://github.com/neurobagel/api/blob/18d5d95ecf8ae6c2ee4b56cbe7a279ef684a8498/app/api/utility.py#L185-L188), the above datasets are never matched by any query sent using the API/query tool.

### More details on the datasets
Here's a gist table https://gist.github.com/alyssadai/40c170e7f79117a276dc1586a1ebf344 with the missing dataset names, URLs, and specific observations on the BIDS data.

Of these, the only dataset where it's not immediately expected that the BIDS data wouldn't be able to be modeled by the CLI is `ds003082`. This one seems to have some problems with how session directories are named in addition to having some imaging files we don't support yet.

### More info
- Here are the types of imaging data the CLI currently models: https://github.com/neurobagel/bagel-cli/blob/main/bagel/mappings.py
- Interestingly, subjects in the missing dataset JSONLD files all seem to have an entry of `"hasSession": []`. This looks to be due to the fact that the `bagel bids` command assigns an empty list by default to this attribute if there are no imaging sessions, https://github.com/neurobagel/bagel-cli/blob/4da00b6db4cce30d40f101c0c4e17be25db3828f/bagel/cli.py#L241-L244. However, the data model for an `nb:Subject` actually states that the `hasSession` value is _optional_ (https://github.com/neurobagel/bagel-cli/blob/4da00b6db4cce30d40f101c0c4e17be25db3828f/bagel/models.py#L61), meaning that we probably don't need to even assign a value if there are no sessions in the first place

### Next steps
We should probably:
- [ ] update the API query template to match subjects without any imaging sessions (i.e., those with only phenotypic data)
- [ ] verify that none of the imaging data types that couldn't be modelled are actually expected to be (or we think _should be_) able to be modelled by the CLI (e.g., `ds003082`)

**Comment by surchs** [comment]
Thanks a lot @alyssadai for all that detective work 🕵‍♀ ! Very cool summary, and I agree we should file these issues. I'll also reference this from https://github.com/neurobagel/planning/issues/67 so we can take another look at it then.

Could you open the two issues you suggested and then I think we can close this issue here 🎉

**Comment by alyssadai** [comment]
Issues to track remaining tasks have been created, so will close this now!
