### ISSUE TITLE
Refactor bug flavours to be more generic and only use type:bug

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#55]
Right now we have a couple of issue types:
- feature
- bug
- maintenance

and then for bug we have a couple of "flavours":
- docs
- functional
- performance
- test
- ux

But e.g. "documentation" already exists as a standalone label. And the other flavours also make sense as qualifiers for other feature or maintenance issues. So I'd say:

- let's make the bug flavours standalone / generic flavours (or reuse existing ones)
- let's only use the `type:bug` label and then explain what kind of bug with the generic qualifiers

existing bug: flavours to make generic:
- performance
- ux - User Experience. quality of life issues

new generic labels to create:
- ui - interface work to make prettier or usable
- dx - developer experience

existing bug flavours to remove:
- functional - not sure what this would be that couldn't also be described by the other labels
- test - already covered by `maint:coverage`

**Comment by surchs** [comment]
We're not going to do this soon, but keeping it open to collect more label-changing thouhts until we decide to take this on

**Comment by alyssadai** [comment]
This is closed by work in https://github.com/neurobagel/planning/issues/7.
