### ISSUE TITLE
Frontend tools UI and QOL improvements

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#59]
## Context
neurobagel/planning#35 gave us the essential annotation tool functionality we need. But our UI is still a bit rough around the edges, and there are some minor UX bugs we'd like to tackle now, because that will make the tool a lot better for little effort. Similarly the query tool is feature complete for a while, but could be improved a lot with some minor UI additions.

## Why
- Part of neurobagel/planning#49 
- to make the Annotation tool an appealing first encounter with Neurobagel (despite being under active development)
- so we can go and ask people to use and give us feedback on the annotation tool
- to make the "federation" and "sample-level" aspects of our query more self evident
- to transparently show our current limitations as beta tools

## Outcomes
- [ ] The annotation tool has no obvious "debug mode" UI elements
- [ ] The visual annotation workflows have minimal context
- [ ] There is a little badge showing that the tools are in beta and will change
- [ ] The query tool UI visually highlights federation and sample information
- [ ] All frontend tools have logos (including the dash)

## What
Annotation tool related
- [x] https://github.com/neurobagel/annotation_tool/issues/612
- [x] https://github.com/neurobagel/annotation_tool/issues/610

Features
- [x] https://github.com/neurobagel/annotation_tool/issues/614
- [x] https://github.com/neurobagel/annotation_tool/issues/620
- [x] https://github.com/neurobagel/annotation_tool/issues/619

Help text

- [x] https://github.com/neurobagel/annotation_tool/issues/611
- [x] https://github.com/neurobagel/annotation_tool/issues/613
- [x] https://github.com/neurobagel/annotation_tool/issues/615
- [x] https://github.com/neurobagel/annotation_tool/issues/617
- [x] https://github.com/neurobagel/annotation_tool/issues/637
- [x] https://github.com/neurobagel/annotation_tool/issues/616

Query related
- [x] https://github.com/neurobagel/api/issues/216
- [x] neurobagel/query-tool#265
- [x] https://github.com/neurobagel/query-tool/issues/219
- [x] https://github.com/neurobagel/query-tool/issues/163
- [x] https://github.com/neurobagel/query-tool/issues/238
- [x] https://github.com/neurobagel/query-tool/issues/284

Universal
- [x] neurobagel/planning#62
- [x] neurobagel/planning#61

Discuss: Annotation tool

Discuss: Query tool

Next:
- [ ] filler
- [ ] https://github.com/neurobagel/annotation_tool/issues/618
- [ ] https://github.com/neurobagel/annotation_tool/issues/236
- [ ] https://github.com/neurobagel/annotation_tool/issues/415

Not planned for now:
- [ ] filler
- [ ] https://github.com/neurobagel/query-tool/issues/108

**Comment by surchs** [comment]
@neurobagel/dev take a look, I think these are the main low hanging UI/UX fruits we can tackle for the most payoff. Let me know what you think, if any should be added, or if some of them have additional dependencies I missed

**Comment by alyssadai** [comment]
Hey @surchs, thanks for putting this together.

I created + added several issues to the annotation tool and query tool sections, and created new ones to discuss if we want to implemented.

**Comment by surchs** [comment]
Closing as completed 🎉
