### ISSUE TITLE
Deploy on Release

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#64]
## Context
It has been quite a while since our tools were released. One reason for that is that we essentially deploy directly to production from the head branch of our tools. With a growing number of remote nodes, that becomes less practical. And it's also a good idea in general to have deterministic deployments, i.e. of specific versions. 

## Why
- Part of neurobagel/planning#49 
- So we have frequent, versioned builds and releases
- So we have a clear language to discuss issues (what version) and node deployments

## Outcomes
- [x] We have a **simple** process to make a release, ideally whenever a small set of new features have accumulated
- [x] On release we tag builds with the new version 
- [x] We have (semi)-automatic processes to deploy newly released versions to production
- [x] Existing processes that deploy directly from the HEAD of the main branch are removed

## What
- [x] neurobagel/api#239
- [x] neurobagel/api#241
  - `neurobagel/api:stable` -> in future, when this moves, we want to give it a `last-stable` or similar tag
  - `neurobagel/api:v0.1.1`

Auto releasing using `auto`:
- We don't want to use the `major` label b/c this will trigger major version bump
- Need to also filter out bot PRs -> this includes dependabot, syncing of workflows
  - https://intuit.github.io/auto/docs/generated/omit-release-notes
- We want to rename the default changelog title sections (based on labels) to something more conventional/informative
  - https://intuit.github.io/auto/docs/configuration/autorc#adding-additional-changelog-title-sections

What we need to do next:
- [x] Manually add `release` label to CLI
- [x] Set flag for creating release only on PRs with `release` back to `true` in CLI
- [x] neurobagel/bagel-cli#259
  - [x] https://github.com/neurobagel/bagel-cli/pull/268 (ensure the plugin uses a different PAT)
- [x] neurobagel/planning#91
- [x] Delete test releases of CLI
- [x] Also, the build on release workflow is not successfully triggered due to automation not being able to trigger workflow, see https://github.com/orgs/community/discussions/25281
  - [x] Solution is, provide a PAT - also fixes our branch protection problem (EDIT: nope, branch protection still blocks the release, so the plugin is still needed)
  - here is the official information on this: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
- [x] Use auto locally to add default release-related labels to `planning` repo and ensure they are propagated
- [x] neurobagel/workflows#43
- [x] neurobagel/workflows#45
- [x] filter out bot PRs + contributions: dependabot, pre-commit, Seb's workflow ones
  - https://intuit.github.io/auto/docs/generated/omit-commits
- [x] add first time contributors section https://github.com/intuit/auto/tree/main/plugins/first-time-contributor
- [x] https://github.com/neurobagel/recipes/issues/9
- [x] update PR template to include check box for PR label

Important reference issues:
- https://github.com/intuit/auto/issues/2412
- https://github.com/intuit/auto/issues/2031
- https://github.com/intuit/auto/issues/2145
- https://github.com/intuit/auto/issues/2377
- https://github.com/intuit/auto/issues/945

Good examples of release workflows: 
- https://github.com/physiopy/phys2bids/blob/master/.github/workflows/auto-release.yml
- https://github.com/dandi/dandi-cli/blob/master/.github/workflows/release.yml

## Related
- [ ] #103
- [x] https://github.com/neurobagel/bagel-cli/issues/236
- [x] https://github.com/neurobagel/bagel-cli/issues/235
- [x] https://github.com/neurobagel/bagel-cli/issues/183
- [ ] https://github.com/neurobagel/api/issues/92
- [ ] https://github.com/neurobagel/proc_dash/issues/104
- [ ] https://github.com/neurobagel/annotation_tool/issues/630

For reference, this is the process that Dandi uses for release automation: https://github.com/dandi/dandi-cli/blob/master/.github/workflows/release.yml

This uses: https://github.com/intuit/auto

Related
- [x] https://github.com/neurobagel/bagel-cli/issues/150

**Comment by alyssadai** [comment]
Closing as all main tasks are complete! 🚀🎉
