### ISSUE TITLE
How do we make breaking changes immediately visible

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#65]
We use semver (and once goes in, this will be meaningful). We are in `"initial development"` which [is defined as](https://semver.org/#spec-item-4)

> Anything MAY change at any time. The public API SHOULD NOT be considered stable.

That's accurate, but maybe not very convenient for users. So we should discuss how we want to highlight meaningful breaking changes. Or if we want to soon move to a major version release and leave the development space.

**Comment by alyssadai** [comment]
Now that we have our auto-release process set up, we can achieve this using our `pr-minor-breaking` and `pr-major-breaking` release labels (see also our template .autorc [here](https://github.com/neurobagel/workflows/blob/main/template_configs/.autorc)). These should automatically organize breaking change PRs under a dedicated section in the changelog.
