### ISSUE TITLE
Refactor issue templates and labels

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#7]
Now that GH has issue types, we should remove the `type:` prefixed labels and their corresponding sub-labels, and replace them with a concise, core set of descriptive labels that provide more detail beyond the issue type, but can be applied to more than one type of issue.

See this [spreadsheet](https://docs.google.com/spreadsheets/d/1m5tYQs8BMoIPBhdx8NJezUtQF5jNuj8SjUWFw_F1jRg/edit?usp=sharing) for a proposal of which labels to remove or replace (and what new labels to add).

For discussion:
There are a bunch of `importance:` and `severity:` labels that we don't use very much. Can we simplify these somehow into a shorter list so there's less ambiguity about what labels to apply?

TODO

- [x] remove the auto-applied prefixes for issue titles, since issue labels/types provide the same info
- [x] add a default issue **type** to issue templates
- [x] as much as possible, rename labels inside https://github.com/neurobagel/planning/labels so they get synced
- [x] Only rename labels without changing their purpose. Otherwise make a new label (otherwise issues that already have the label applied might not make sense anymore)
- [x] for labels that get fully removed, first remove them from planning, and then remove them from all other repos manually
- [x] if a to-be-deleted label has issues assigned, decide what the best new label is. If one fits, apply that instead. Otherwise simply remove label
- [x] Remove the blank issue template (GH seems to provide one automatically now)

**Comment by surchs** [comment]
Thanks @alyssadai. Went through the spreadsheet, agree with the proposal. @rmanaem please check out before standup so we can decide then and implement

**Comment by surchs** [comment]
> add a default issue type to issue templates

Hey @alyssadai: I don't think that works yet - maybe because issue types are still in beta. Have you seen somewhere how to add the type to the template?

**Comment by alyssadai** [comment]
@surchs, see the syntax suggested here: https://github.com/orgs/community/discussions/112806#discussioncomment-9909487 !

**Comment by surchs** [comment]
also: https://github.com/neurobagel/planning/issues/55

**Comment by surchs** [comment]
> add a default issue type to issue templates
I don't think this currently possible - unless we go back to having a blank issue template.

**Comment by alyssadai** [comment]
Hey @surchs, thanks so much for addressing this!! The new issue labels are looking ✨ great ✨. Big thanks for updating the labels on our existing issues also 💪 

In terms of reviewing this issue, I double checked the updated label list in `neurobagel/planning` against our label spreadsheet and everything makes sense to me. I do have a few clarification questions / comments before we merge:
- You decided to keep the `severity:` labels for now instead of turning that into a project field, right? That's fine with me, just wanted to double check.
- What was the issue with renaming `flag:blocker` to `blocker`? Not a big deal, just curious.
- I saw you commented in the spreadsheet:
  > deprecate and remove are different things. So let's have two labels

  but I only see the new `deprecation` label. Just to confirm: is it okay if we use this for both feature deprecation and/or removal?
- Did you update the colors for the `pr-` / release labels by any chance? That's fine, but since the labels are originally configured/generated from .autorc, I'd suggest also updating the label colors here:
https://github.com/neurobagel/workflows/blob/main/template_configs/.autorc
so they don't go out of sync in case we ever need to regenerate the labels

**Comment by alyssadai** [comment]
Also, in terms of the checkbox:

> add a default issue type to issue templates

I think this is complete via your PR https://github.com/neurobagel/.github/pull/17. To clarify, I did not mean we should have a default issue type for every new issue opened, only that there should be an issue type for each issue *template* we have (instead of a label). :)
