### ISSUE TITLE
last sync seems to have failed (for menu repo)

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#76]
main suspect:
- PATs with wrong permissions

see https://github.com/neurobagel/documentation/wiki/How-we-work#updating-the-personal-access-tokens (and update if something is wrong).

Steps:
- [x] rename global org PATs to something more intuitive
- [x] recreate global PATs with correct permissions
- [x] rename all workflows to use these new, renamed PATs
- [x] update the wiki / docs to explain what permissions the PATs need (and their names) and how to refresh them
- [x] confirm the workflows are running
- [ ] ... ?

**Comment by surchs** [comment]
Updated the PAT permission descriptions: https://github.com/neurobagel/documentation/wiki/How-we-work#updating-the-personal-access-tokens

**Comment by alyssadai** [comment]
Thanks for the detailed documentation of the PATs @surchs! 🎉 

One 🍒: maybe worth mentioning in the description that these are fine-grained PATs and not basic ones?

Otherwise, workflows and label syncing seem to be running as expected, so I think this is good to close :)

**Comment by surchs** [comment]
you mean that they are fine-grained PATs? Yeah, good idea, I'll add that!
