### ISSUE TITLE
automatic processing of OpenNeuro annotations

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#77]
# Context
We now have https://github.com/OpenNeuroDatasets-jsonld for OpenNeuro forks. But so far everything happens manually (pushing a change, pulling in an upstream change, listening to a change and then processing the new version). Now we want things to happen automatically.

https://hackmd.io/bbi4VBoGREyb4m820coQww

# Why
- Part of #11 and #49 
- Follows #38 
- So I can  annotate a single OpenNeuro dataset when I have a moment, and then 
- let the bots take care of the rest so that I can then find it in the federation search

# Outcomes
- [x] there is a fork in https://github.com/OpenNeuroDatasets-jsonld for every OpenNeuro dataset
- [x] when upstream changes, that change automatically makes it into the fork (e.g. cron job)
- [x] when we (semi-) manually push to the fork from our side (e.g. to add annotations), this gets combined into a shared history
- [x] when either upstream or direct changes happen to the default branch of the fork, a CI job processes the entire fork with the neurobagel CLI and makes a .jsonld file ready for the graph
  - we need help on this one
  - we know where to run the CLI (with enough resources) + where outputs should be stored (outputs should be all in one repo)
- [x] that new .jsonld file is then stored somewhere we can easily (ideally automatically) pick it up to push it into the graph
- [x] neurobagel/tools#19

# What
- [x] https://github.com/OpenNeuroDatasets-JSONLD/.github/issues/16
- [x] https://github.com/neurobagel/bagel-cli/issues/183

**Comment by alyssadai** [comment]
Here's our tentative script to run the CLI on one dataset: https://github.com/neurobagel/bulk_annotations/blob/main/datalad_get_single_dataset.sh

**Comment by alyssadai** [comment]
See also https://github.com/neurobagel/documentation/wiki/Annotating-OpenNeuro-datasets

**Comment by rmanaem** [comment]
![Image](https://github.com/neurobagel/planning/assets/77515879/1e2f8272-310c-44fd-b820-172cdea450eb)

**Comment by rmanaem** [comment]
Closing this as complete as all desired outcomes have been achieved.
