### ISSUE TITLE
Store new example fed.env file in to-be-created config file repository

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#82]
As discussed in https://github.com/neurobagel/api/issues/162 we need to store a copy of the new federation-API docker-compose file in the yet-to-be-created "recipe" repo so user can easily download and use it.

_Originally posted by @surchs in https://github.com/neurobagel/documentation/pull/133#discussion_r1402782925_

**Comment by alyssadai** [comment]
Duplicate of https://github.com/neurobagel/planning/issues/80, I think
