### ISSUE TITLE
Session Level Pheno

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#83]
# Context
We have a good amount of data in our nodes and are starting to also host richer data. Many of the richer data have at least some longitudinal information on phenotypic data - and we cannot model this because we model phenotypic information at the subject level. This will allow us to provide much richer queries in the near future and is, from the tool and data model side, a relatively easy thing to do. 

There is also [BEP36 making its way towards completion](https://docs.google.com/document/d/1WTkfES8L0vItZVyyR68fc-9cO03jS-kCnMnw6602pbc/edit?usp=sharing), and we want to both have some ideas on that and be able to model BEP36 information once it merges.

The overall design ideas live here: https://miro.com/app/board/uXjVNIzFV9w=/

IMportant stuff
- right now the CLI **can** handle multiple sessions (rows about the same subject), but it just picks the first value

# Why
- Part of neurobagel/planning#11 
- Follows neurobagel/planning#64 
- We want to model longitudinal data so we can represent richer information and query them
- So we can get more value from our own (PD) datasets locally
- To get ready for such modeling challenges as QPN where imaging and pheno sessions can be completely separate

# Outcomes
- [x] our data model schema supports age, sex, diagnosis, assessment at the session level
- [x] all (of our own) graphs are running up to date data models (no more subject level pheno)
- [x] I can search for a subject with 2 phenotypic sessions and no imaging
- [x] I can annotate (annotation tool) and process (CLI) a table with session ID columns

# What
CLI
- [x] neurobagel/bagel-cli#257
- [x] https://github.com/neurobagel/bagel-cli/issues/225
- [x] figure out if "session id" should be optional or not

Annotation tool
- [x] neurobagel/annotation_tool#663

"Work"
- ~[ ] update the data dictionaries for everything in OpenNeuro (because that schema has changed)~
- ~[ ] neurobagel/query-tool#58~
- [x] https://github.com/neurobagel/planning/issues/107

API
- [x] neurobagel/api#249
- [x] neurobagel/api#262
- [x] https://github.com/neurobagel/api/issues/271

Federation API
- [x] https://github.com/neurobagel/federation-api/issues/60

Query tool
- [x] neurobagel/planning#86
- [x] https://github.com/neurobagel/query-tool/issues/78

Documentation-related
- [x] https://github.com/neurobagel/neurobagel_examples/issues/26
- [x] https://github.com/neurobagel/documentation/issues/157

# What it is not
- we do not deal with session timing information (i.e. imaging and pheno happening within X days of each other)
- we do not support multiple session naming systems, if you have an imaging session, it has to be named in the big input .tsv
- allowing multiple columns "about" age or "sex" (different values for different sessions have to still be encoded longform)
- any information on ordering of sessions or "baseline" sessions

To close it all out
- [x] #135

**Comment by rmanaem** [comment]
Since there were no issues open on the annotation tool and query tool related to this roadmap, I'm turning the checkboxes into issues for both tools.

**Comment by alyssadai** [comment]
Closing as all issues have been addressed! 🥳
