### ISSUE TITLE
Clean up GDrive

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#84]
https://drive.google.com/drive/folders/1RzEXyYQ3cB4fPmpMZroqN6R5k3D-mXDo?usp=drive_link is a bit of a mess right now. One of the things we need and don't have is a nice place for meeting minutes that is easy to find and reuse, so we all know where to look for the newest info on projects.

I think we should:

- [x] have only a few top-level directories
- [x] have one main dir for all projects
- [x] have the minutes for all active projects in an easily accessible place
- [ ] ~some other thing~

### NEW DIRECTORY STRUCTURE (see our Drive)
- `Collaborations/` : under the relevant category folder, there's a subdirectory for each project containing  * **shared meeting minutes** * and other notes about the collaboration
  - `Active/`
  - `Archive/`
  - `Prospective/`
  - **Contents potentially shared with external collaborators? YES**
- `Conferences/`
  - Abstracts, posters, and other conference materials, each organized in a separate subdirectory with the conference name + year
- `Graphics/`
  - Miscellaneous tool screenshots, our logo, funder logos, + other images that can be reused in slideshows, conference posters, etc.
- `Presentations/`
  - Slideshows for meetings, organized by year
  - **One dedicated subdirectory for `Lab/advisory meetings/`**
- `Internal/` : team-facing notes
  - `Design/`: catch-all subdirectory for notes from issue planning/data modeling/Neurobagel tool documentation drafts, etc. that is part of our process but that we probably won't revisit in the future
  - `Resources/`: Developer-facing notes of things learned from the various software/tools we use (e.g., GitHub tips and tricks)
  - `Research/`: Notes from research on Neurobagel-adjacent stuff (e.g. similar projects, non-for-profit info), that serves as a reference for the team
  - `Minutes (internal)/`: Meeting minutes from our team meetings, advisory board meetings, copies of team-facing notes on external meetings
  - **Contents potentially shared with external collaborators? NO**

### "I need to create some meeting minutes - where do they go?"
Is the meeting with non-team members for a collaboration?
  - YES
    - Is it for an existing collaboration?
      - YES: Under the appropriate collaboration subdirectory in `Collaborations/`, either add to the running minutes document if it exists, or create a new meeting minutes document (which you will continue adding to in the future). If the minutes for the meeting must be a standalone document in the directory, make sure it is dated.
      - NO: Create a subdirectory under `Collaborations/` (either under `Prospective/` or `Active/`) with the name of the collab. Inside the subdirectory, create a new running meeting minutes document.
  ** _If you need to also take notes on the meeting that are only team-facing/internal, save it into a doc in `Internal/Minutes (internal)/` with the name of the collab in the document title_
  - NO
    - Assuming the meeting is either with team members or an advisory board meeting, use the `Internal/Minutes (internal)` directory

**Comment by surchs** [comment]
Thanks @alyssadai! I like the structure! I would differentiate between "Projects" and "Collaborations":

- Projects - internal things like the federation API or designing some architecture?
- Collaborations - something longer-term outside of the lab / team, e.g. Douglas, NIMHANS, ...

wdyt?

**Comment by alyssadai** [comment]
@surchs, @rmanaem, I've updated the issue description with the new directory structure I've implemented, including what each directory is expected to contain. Please have a read through/look and let me know if anything seems unreasonable.

The new structure also specifies where different types of meeting minutes should go, which I also lay out in the `"I need to create some meeting minutes - where do they go?"` section at the bottom of the issue.

I've kept 5 top-level directories as my sense is any more levels of depth will make it too tedious to find what we're looking for (since there are already many subdirectories for different projects, years/dates of presentations, etc.). Presentations + Collaborations are among our most visited locations I think, so I have kept those among the 5.

If you agree with the structure, please gives a thumbs up or otherwise let me know - and hopefully we can close this issue this week!

**Comment by rmanaem** [comment]
Thanks @alyssadai! The new structure looks good to me. I only have one note, I believe we can remove `Internal/Research` as it has been replaced by our wiki.

**Comment by surchs** [comment]
Looks good @alyssadai, I'm all in favor. For the Internal/Research portion, I think it can still make sense to have a GDrive for this, because we need to have a place to collect our findings and collaborate on things before they go into the wiki. 

We should definitely move things into the wiki whenever we can, but I'd say let's keep this folder around for a bit and see if we use it.

**Comment by surchs** [comment]
🧑‍🍳 I think this is good to close now

**Comment by alyssadai** [comment]
Thanks for the feedback @surchs and @rmanaem!

I'll keep the `Internal/Research` directory for now then both as an archive and in case we need somewhere to drop more drafty/unorganized notes of topics we're researching.

Happy to amend the structure in future as needed.
