### ISSUE TITLE
Replace coveralls with codecov

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#89]
Coveralls has recently become a source of flaky tests which is occasionally annoying. We could probably find ways to fix this. But the main reason we started with coveralls over codecov was because Alyssa's github account didn't play nice with Codecov - and that has since been fixed.

I personally prefer the code reports from codecov. So I propose we start migrating to codecov and replace coveralls.

**Comment by surchs** [comment]
e.g. https://github.com/neurobagel/bagel-cli/actions/runs/7197612436/job/19605132564?pr=252#step:7:79

**Comment by alyssadai** [comment]
Duplicate of #173 

(side note: love how many times we opened related issues about this 😆)
