### ISSUE TITLE
Investigate alternatives to Stardog as a graph backend

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#9]
Stardog seems to be silently moving from their "free 1-year academic license" to short-term "trials", and increasingly push users towards their cloud offerings. We therefore need to explore alternatives for our graph backend that we can suggest to prospective new endpoints.

Here are some constraints for the graph backends:

**must have's**: 

- native RDF support. I.e. not labeled property graphs. RDF gives us W3C standards compliance and better interoperability with existing vocabularies. Sadly most OSS graphs are LPGs :(. Can discuss this, but very unlikely to change
- SPARQL 1.1 support. This is likely a given for most RDF graphs. We need 1.1. for federation support: https://www.w3.org/TR/sparql11-query/
- perpetual free academic license, implicit license, or full OSS
- official docker image
- actively maintained (i.e. functional PR merges within the last year), ideally with institutional backing

**Nice to have's**:

- Decent documentation of the SPARQL HTTP API. We'll at least want to have clear descriptions for 
  - database creation
  - data upload
  - drop graph
  - SPARQL query endpoint
- Performant. Stardog sadly seems to be leading the field in query performance, so let's say no less than 50% of Stardog's performance would be good.

Here is a list of our potential candidates: https://db-engines.com/en/ranking/rdf+store

**Comment by alyssadai** [comment]
@neurobagel/dev should we close this now that we have completed migrated to GraphDB? If we need further alternatives in the future, we can re-open or create a new issue.
