### ISSUE TITLE
Customize changelog section titles

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#91]
### What
In the .autorc file, we should update the change type labels such that:
- `major`, `minor` are called something else, so that they don't conflict with dependabot
  - see https://github.com/intuit/auto/issues/2412
- we should also try to:
  - create more **custom labels** to have better coverage of our existing PR prefixes
  - update the resulting changelog **titles** so they correspond to the sections we want, e.g.:
    - https://github.com/neurobagel/documentation/wiki/Release-process#example-release-notes-template
  
See https://intuit.github.io/auto/docs/configuration/autorc#adding-additional-changelog-title-sections

### Steps to implement

<details open>
  <summary>Full configuration of custom PR labels (part of .autorc file) </summary>

  ```bash
      {
        "name": "pr-major-breaking",
        "changelogTitle": "💥 Breaking Changes",
        "description": "Significant behaviour change that breaks compatibility, will increment major version (+1.0.0)",
        "releaseType": "major",
        "overwrite": true,
        "color": "#C5000B"
      },
      {
        "name": "pr-minor-breaking",
        "changelogTitle": "💥 Breaking Changes",
        "description": "Feature or enhancement that breaks compatibility, will increment minor version (0.+1.0)",
        "releaseType": "minor",
        "overwrite": true,
        "color": "#F1A60E"
      },
      {
        "name": "pr-minor",
        "changelogTitle": "🚀 Enhancements",
        "description": "Non-breaking feature or enhancement, will increment minor version (0.+1.0)",
        "releaseType": "minor",
        "overwrite": true,
        "color": "#F1A60E"
      },
      {
        "name": "pr-patch",
        "changelogTitle": "🚀 Enhancements",
        "description": "Incremental feature improvement, will increment patch version when merged (0.0.+1)",
        "releaseType": "patch",
        "overwrite": true,
        "default": true,
        "color": "#870048"
      },
      {
        "name": "pr-bug-fix",
        "changelogTitle": "🐛 Bug Fixes",
        "description": "Bug fix, will increment patch version when merged (0.0.+1)",
        "releaseType": "patch",
        "overwrite": true,
        "color": "#870048"
      },
      {
        "name": "pr-documentation",
        "changelogTitle": "📝 Documentation",
        "description": "Change that only affects user documentation",
        "releaseType": "none",
        "overwrite": true,
        "color": "#cfd3d7"
      },
      {
        "name": "pr-tests",
        "changelogTitle": " 🧪 Tests",
        "description": "Add or improve existing tests",
        "releaseType": "none",
        "overwrite": true,
        "color": "#ffd3cc"
      },
      {
        "name": "pr-internal",
        "changelogTitle": "🏠 Internal",
        "description": "Non-user-facing code improvement, will increment patch version when merged (0.0.+1)",
        "releaseType": "patch"
        "overwrite": true,
        "color": "#696969"
      },
      {
        "name": "pr-dependencies",
        "changelogTitle": "🔩 Dependency Updates",
        "description": "Update one or more dependencies version",
        "releaseType": "none",
        "overwrite": true,
        "color": "#8732bc"
      },
      {
        "name": "pr-performance",
        "changelogTitle": "🏎 Performance Improvements",
        "description": "Improve performance of an existing feature, will increment patch version when merged (0.0.+1)",
        "releaseType": "patch",
        "overwrite": true,
        "color": "#f4b2d8"
      },
      {
        "name": "skip-release",
        "description": "PR doesn't appear in the changelog and preserves current version when merged",
        "releaseType": "skip",
        "overwrite": true,
        "color": "#bf5416"
      },
      {
        "name": "release",
        "description": "Create a release when this PR is merged",
        "releaseType": "release",
        "overwrite": true,
        "color": "#007f70"
      }
  ```
</details>

- [x] we want to override the default labels entirely: https://intuit.github.io/auto/docs/configuration/autorc#overriding-default-labels
- [ ] delete the 7 existing default labels created by auto that we don't need (note that we'll continue to use the `documentation` label for issues):

LABELS TO DELETE:
  1. major
  2. minor
  3. patch
  4. internal
  5. tests
  6. dependencies
  7. performance

@alyssadai:
  - [x] bagel-cli
  - [x] api
  - [x] federation-api
  - [x] digest
  - [x] planning
  - [x] workflows
  - [x] documentation
  - [x] bagelschema
  - [x] project

@rmanaem 
  - [x] query-tool
  - [x] annotation_tool
  - [x] react-query-tool
  - [x] neurobagel_examples
  - [x] menu

@surchs:
  - [x] recipes
  - [x] openneuro-annotations
  - [x] dataget
  - [x] browbids
  - [x] bulk_annotations

- Document in internal wiki:
  - [x] How to create the labels locally (link new .autorc once it's been made available in repos)
  - [x] How to use new PR labels
  - [x] How to add release notes summary! super cool https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes PR labels

**Comment by alyssadai** [comment]
@neurobagel/dev, I've assigned each of you repos to delete the leftover PR labels (7 total) from our initial auto setup from.

Please check off the repos when you have finished the deletion :) thanks so much for your help!!

**Comment by alyssadai** [comment]
FOR REVIEWER:

- Have a quick look at the final label configuration in the issue description and/or the newly created `pr-` prefixed labels in this repo
- See https://github.com/neurobagel/documentation/wiki/Release-process#auto-releasing-using-intuitauto for my internal documentation on how `auto` uses PR labels, and how to set up a release

**Comment by surchs** [comment]
Just occured to me:

```bash
#!/bin/bash

for repo in recipes workflows documentation bagelschema project recipes openneuro-annotations;
do
    for label in performance dependencies;
    do

        gh label delete $label -R neurobagel/$repo --yes
    
    done
done
```
and so on

**Comment by surchs** [comment]
Very nice writeup @alyssadai ! docs look good, labels are gone (script may be slightly overzealous in hindsight, it also wiped out all `documentation` labels ... oh well).

Good to go, I think 🧑‍🍳

**Comment by alyssadai** [comment]
@surchs the script is a great idea! 💯

You beat me to it - I ended up with the following script to delete labels from repos only if they matched the exact label name, color, and description from a specified list. Aka, the more paranoid version of your script above 😛

I tested it by creating the exact same toy labels in a couple of repos and it seems to work well.

```bash
#!/bin/bash

REPOS=$(gh repo list neurobagel --json name | jq -r '.[].name')

# NOTE: the color is case-sensitive in the matching, and should not have # in front of it
LABELS_TO_DELETE=(
	"labelone,c5def5,test label 1"
	"labeltwo,7D939A,test label 2"
)

# NOTE: make sure ${REPOS} doesn't have quotes around it
for repo in ${REPOS}; do
	echo "Processing repository: ${repo}..."

	for label in "${LABELS_TO_DELETE[@]}"; do
		# Get the label attributes
		IFS="," read -r label_name label_color label_description <<< "$label"
		
		# Check if the label exists with the specified name, color, and description
		# NOTE: we set the label limit -L to something pretty big to ensure all existing labels are fetched
		gh label list -R "neurobagel/${repo}" -L 200 --json name,color,description | jq -e ".[] | select(.name == \"$label_name\" and .color == \"$label_color\" and .description == \"$label_description\")" >/dev/null

	if [ $? -eq 0 ]; then
      		gh label delete "$label_name" --repo "neurobagel/${repo}" --yes
    	else
      		echo "Label not found: $label_name"
    	fi
  	done

  	echo -e "Finished processing repository: ${repo}\n"
 done
```

Also, what did you mean by the following:
> script may be slightly overzealous in hindsight, it also wiped out all `documentation` labels

?

From what I can tell your script doesn't have `documentation` in the list to delete - how would it have wiped these? 😮

**Comment by alyssadai** [comment]
Closing as this is now completed!
