### ISSUE TITLE
Migrate OpenNeuro node to graphDB

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#93]
Our stardog license is expiring at the end of the month. We have to migrate the OpenNeuro node to a different graph backend by then to avoid it crashing. This will also give us an opportunity to see what the impact on performance is - and react if performance gets a lot worse.

This issue does not involve updating the OpenNeuro data in any way.

### Steps to implement
On the `fairmount` machine:
- [x] update the `.env` file for the OpenNeuro node API (at `~/projects/bagelapi`) for a GraphDB backend, according to [these instructions](https://neurobagel.org/infrastructure/#__tabbed_3_2)
  - [x] set some new sensible credentials
- [x] relaunch the API + graph server
- [x] create a new GraphDB database on the `fairmount` machine called `open_neuro`, following the instructions in our docs
- [x] use `add_data_to_graph.sh` to upload the JSONLD files in `~/data/openneuro-annotations` to the newly created database, making sure `--use-graphdb-syntax` is used
- [x] add vocab files to graph
- [x] update OpenStack security rules if needed (add GraphDB external access rule to `fairmount`)

**Comment by alyssadai** [comment]
For reviewer, for a sanity check:
- [ ] try running a sample query/testing out one of the vocab endpoints at https://api.neurobagel.org 
- [ ] on the `fairmount` machine, check the running Docker containers and the `.env` file at `~/projects/bagelapi/.env`

Some notes:
- 340/341 OpenNeuro datasets with JSONLD files were uploaded to the graph successfully. One (ds002000) failed for the same reason it did during the last update, see https://github.com/neurobagel/planning/issues/50#issuecomment-1788354827
  - this limitation is also noted here: https://github.com/neurobagel/planning/issues/67
- We should write a bash script for the first-time graph server setup and database creation, ideally that uses values from the `.env` file users already create for the API

**Comment by surchs** [comment]
All looks good @alyssadai, thanks a lot for switching us over!

One thing I noticed is that the new node API for OpenNeuro on fairmount is running the [`latest` docker tag for the API](https://hub.docker.com/layers/neurobagel/api/latest/images/sha256-4bd118435e0f5a9035ad2899a67feea3fb47865649c94721200a8fcfe9b57383?context=repo) which is now a bit older than `stable`:

```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED        STATUS        PORTS                                                 NAMES
6f70571710d8   neurobagel/api:latest                  "/bin/sh -c 'uvicorn…"   9 hours ago    Up 9 hours    0.0.0.0:8000->8000/tcp, :::8000->8000/tcp             bagelapi-api-1
c6232c905035   ontotext/graphdb:10.3.1                "/opt/graphdb/dist/b…"   9 hours ago    Up 9 hours    0.0.0.0:7200->7200/tcp, :::7200->7200/tcp, 7300/tcp   bagelapi-graph-1
296776f9111c   neurobagel/federation_api              "/bin/sh -c 'uvicorn…"   8 days ago     Up 8 days     0.0.0.0:8080->8000/tcp, :::8080->8000/tcp             federation
db1a58860aa0   neurobagel/api:nightly                 "/bin/sh -c 'uvicorn…"   2 months ago   Up 2 months   0.0.0.0:8888->8000/tcp, :::8888->8000/tcp             api-api-1
953a4d01722a   stardog/stardog:8.2.2-java11-preview   "/opt/stardog/bin/st…"   2 months ago   Up 2 months   0.0.0.0:5821->5820/tcp, :::5821->5820/tcp             api-graph-1

```
Unless there's a reason for that, I'd say let's relaunch it with `stable` and then stick with that. Other than that we can close this! 🎉
